apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-admin-serviceaccount
  namespace: ingress-admin
  labels:
    app.kubernetes.io/name: ingress-admin
    app.kubernetes.io/part-of: ingress-admin

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-admin-clusterrole
  labels:
    app.kubernetes.io/name: ingress-admin
    app.kubernetes.io/part-of: ingress-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ingress-admin-role
  namespace: ingress-admin
  labels:
    app.kubernetes.io/name: ingress-admin
    app.kubernetes.io/part-of: ingress-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the ingress-admin-controller.
      - "ingress-controller-leader-nginx"
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-admin-role-nisa-binding
  namespace: ingress-admin
  labels:
    app.kubernetes.io/name: ingress-admin
    app.kubernetes.io/part-of: ingress-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-admin-role
subjects:
  - kind: ServiceAccount
    name: ingress-admin-serviceaccount
    namespace: ingress-admin

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-admin-clusterrole-nisa-binding
  labels:
    app.kubernetes.io/name: ingress-admin
    app.kubernetes.io/part-of: ingress-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-admin-clusterrole
subjects:
  - kind: ServiceAccount
    name: ingress-admin-serviceaccount
    namespace: ingress-admin

---

