apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-admin-controller
  namespace: ingress-admin
  labels:
    app.kubernetes.io/name: ingress-admin
    app.kubernetes.io/part-of: ingress-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-admin
      app.kubernetes.io/part-of: ingress-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-admin
        app.kubernetes.io/part-of: ingress-admin
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
    spec:
      # wait up to five minutes for the drain of connections
      terminationGracePeriodSeconds: 300
      serviceAccountName: ingress-admin-serviceaccount
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: ingress-admin-controller
          #image: quay.io/kubernetes-ingress-controller/ingress-admin-controller:1.1
          image: docker.io/liyinda/ingress-admin:1.1
          imagePullPolicy: Always
          args:
            - /backend
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            # www-data -> 101
            runAsUser: 101
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8888
            - name: https
              containerPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /vue
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /vue
              port: 8888
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - /wait-shutdown

---

